# Generated by Django 2.2.28 on 2024-03-22 11:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminID', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.IntegerField(unique=True)),
                ('author', models.CharField(max_length=50)),
                ('coverPhoto', models.ImageField(upload_to='book_images')),
                ('views', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField()),
                ('totalPages', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryID', models.CharField(max_length=20, unique=True)),
                ('numOfBooks', models.IntegerField(default=0)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['categoryID'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilePic', models.ImageField(blank=True, upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewID', models.CharField(max_length=50, unique=True)),
                ('message', models.CharField(max_length=50, unique=True)),
                ('dateWritten', models.DateField(auto_now_add=True)),
                ('edited', models.BooleanField(default=False)),
                ('reviewAuthorFK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reviewBookFK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mylibrary.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateSet', models.DateTimeField()),
                ('achieved', models.BooleanField()),
                ('goalID', models.CharField(max_length=50, unique=True)),
                ('numPages', models.IntegerField(null=True)),
                ('dateDue', models.DateTimeField(default=datetime.datetime(2024, 3, 22, 11, 52, 57, 912409))),
                ('slug', models.SlugField(unique=True)),
                ('goalAuthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BooksUserReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startedReading', models.DateTimeField(null=True)),
                ('pagesRead', models.IntegerField(null=True)),
                ('bookFK', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mylibrary.Book')),
                ('userFK', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mylibrary.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(to='mylibrary.Category'),
        ),
        migrations.AddField(
            model_name='book',
            name='uploadedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
