# Generated by Django 2.2.28 on 2024-03-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='totalPages',
            field=models.IntegerField(null=True),
        ),
    ]
