# Generated by Django 2.2.28 on 2024-03-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0002_auto_20240320_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksuserreading',
            name='pagesRead',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
