# Generated by Django 2.2 on 2024-03-06 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0002_auto_20240305_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='uploadedBy',
        ),
    ]
