# Generated by Django 2.2.28 on 2024-03-21 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0002_auto_20240321_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='dateDue',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 21, 16, 1, 59, 703661)),
        ),
    ]
