# Generated by Django 2.2 on 2024-03-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0002_auto_20240315_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='goalName',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
