# Generated by Django 2.2 on 2024-03-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0003_goal_goalname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='goalID',
        ),
        migrations.AddField(
            model_name='goal',
            name='ISBN',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goal',
            name='goalName',
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
    ]
