# Generated by Django 2.2.28 on 2024-03-21 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0003_auto_20240321_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='totalPages',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='dateDue',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 21, 16, 3, 9, 490581)),
        ),
    ]
