# Generated by Django 2.2.28 on 2024-03-21 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0004_userprofile_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profileLink',
        ),
    ]
