# Generated by Django 2.2.28 on 2024-03-21 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0005_remove_userprofile_profilelink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='slug',
        ),
    ]
