# Generated by Django 2.2.28 on 2024-03-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0005_review_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='dateWritten',
            field=models.DateField(auto_now_add=True),
        ),
    ]
