# Generated by Django 2.2.28 on 2024-03-21 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0006_remove_userprofile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksuserreading',
            name='userFK',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mylibrary.UserProfile'),
        ),
    ]
