# Generated by Django 2.2 on 2024-03-07 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0006_auto_20240307_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='uploadedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mylibrary.UserProfile'),
        ),
    ]
