# Generated by Django 2.2.28 on 2024-03-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0007_auto_20240321_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksuserreading',
            name='pagesRead',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='booksuserreading',
            name='startedReading',
            field=models.DateTimeField(null=True),
        ),
    ]
