# Generated by Django 2.2.28 on 2024-03-20 08:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mylibrary', '0008_auto_20240318_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='coverPhoto',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
        migrations.RemoveField(
            model_name='book',
            name='uploadedBy',
        ),
        migrations.AddField(
            model_name='book',
            name='uploadedBy',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
