# Generated by Django 2.2 on 2024-03-07 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0008_auto_20240307_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='uploadedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
