# Generated by Django 2.2.28 on 2024-03-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0009_auto_20240320_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='coverPhoto',
            field=models.ImageField(blank=True, upload_to='book_images'),
        ),
    ]
