# Generated by Django 2.2.28 on 2024-03-20 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mylibrary', '0010_auto_20240320_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='uploadedBy',
        ),
        migrations.AddField(
            model_name='book',
            name='uploadedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
