# Generated by Django 2.2.28 on 2024-03-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0011_auto_20240320_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='coverPhoto',
            field=models.ImageField(upload_to='book_images'),
        ),
    ]
