# Generated by Django 2.2.28 on 2024-03-21 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0014_auto_20240321_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 21, 12, 31, 28, 842843)),
        ),
    ]
