# Generated by Django 2.2.28 on 2024-03-21 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0015_goal_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='dateDay',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='dateMonth',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='dateYear',
        ),
        migrations.AlterField(
            model_name='goal',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 21, 13, 5, 47, 865911)),
        ),
    ]
