# Generated by Django 2.2.28 on 2024-03-21 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0016_auto_20240321_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='date',
        ),
        migrations.AddField(
            model_name='goal',
            name='dateDue',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 21, 13, 31, 28, 85266)),
        ),
    ]
