# Generated by Django 2.2.28 on 2024-03-22 05:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0017_auto_20240321_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='dateDue',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 5, 58, 12, 866924)),
        ),
    ]
